swagger:
  enable: true
  url: localhost:8686

spring:
  datasource:
    url: jdbc:mysql://129.211.97.13:3306/young?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: young0110

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
