swagger:
  enable: true
  host: localhost:8686
  base-package: com.spring.demo.controller

#spring:
#  datasource:
#    url: jdbc:mysql://url:port/database?serverTimezone=GMT%2B8&useSSL=false
#    username: username
#    password: password