server:
  port: 8686

spring:
  redis:
    host: 127.0.0.1
    #password: 123456
    port: 6379
    database: 0
    timeout: 60
    jedis:
      pool:
        max-active: 10
        max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200 #连接池最大空闲连接
        min-idle: 0   #连接池最小空闲连接
    block-when-exhausted: true
